#!/bin/sh

tentakel pkill chrome -HUP

global_param="--window-size=1366,768 --kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-translate"

UDD=$HOME/.config/chrome-nfs/orion00-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-00 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=0'" &
ssh -fx orion-00 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion00-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-00 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=1'" &

UDD=$HOME/.config/chrome-nfs/orion00-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-00 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=2'" &

UDD=$HOME/.config/chrome-nfs/orion01-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-01 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=3'" &
ssh -fx orion-01 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion01-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-01 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=4'" &

UDD=$HOME/.config/chrome-nfs/orion01-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-01 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=5'" &

UDD=$HOME/.config/chrome-nfs/orion02-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-02 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=6'" &
ssh -fx orion-02 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion02-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-02 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=7'" &

UDD=$HOME/.config/chrome-nfs/orion02-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-02 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=8'" &

UDD=$HOME/.config/chrome-nfs/orion03-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-03 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=9'" &
ssh -fx orion-03 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion03-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-03 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=10'" &

UDD=$HOME/.config/chrome-nfs/orion03-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-03 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=11'" &

UDD=$HOME/.config/chrome-nfs/orion04-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-04 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=12'" &
ssh -fx orion-04 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion04-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-04 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=13'" &

UDD=$HOME/.config/chrome-nfs/orion04-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-04 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=14'" &

UDD=$HOME/.config/chrome-nfs/orion05-0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-05 "env DISPLAY=:0.0 google-chrome $param 'http://10.0.8.100:9090?clientID=15'" &
ssh -fx orion-05 "sleep 5; ./move_mouse" &

UDD=$HOME/.config/chrome-nfs/orion05-1
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-05 "env DISPLAY=:0.1 google-chrome $param 'http://10.0.8.100:9090?clientID=16'" &

UDD=$HOME/.config/chrome-nfs/orion05-2
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
ssh -fx orion-05 "env DISPLAY=:0.2 google-chrome $param 'http://10.0.8.100:9090?clientID=17'" &
