#!/bin/sh

tentakel pkill chrome -HUP

global_param="--kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files"

for i in {1..36}
do
	node=`printf lyra-%02d $i`
	
	UDD=$HOME"/.config/chrome-nfs/"$node"A"
	mkdir -p $UDD/Default
	param="$global_param --user-data-dir=$UDD"
	client=$(expr $(expr $i - 1) \* 2)
	ssh -fx $node "env DISPLAY=:0.0 google-chrome $param 'http://lyra.evl.uic.edu:9090?clientID=$client'" &
	
	UDD=$HOME"/.config/chrome-nfs/"$node"B"
	mkdir -p $UDD/Default
	param="$global_param --user-data-dir=$UDD"
	client=$(expr $client + 1)
	ssh -fx $node "env DISPLAY=:0.1 google-chrome $param 'http://lyra.evl.uic.edu:9090?clientID=$client'" &
done
