#!/bin/sh

UDD=$HOME/.config/chrome-nfs/thor0
param="--kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-webgl --enable-accelerated-compositing --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param 'http://127.0.0.1:9090?clientID=0' &

UDD=$HOME/.config/chrome-nfs/thor1
param="--kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-webgl --enable-accelerated-compositing --user-data-dir=$UDD"
env DISPLAY=:0.1 google-chrome $param 'http://127.0.0.1:9090?clientID=1' &

UDD=$HOME/.config/chrome-nfs/thor2
param="--kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-webgl --enable-accelerated-compositing --user-data-dir=$UDD"
env DISPLAY=:0.2 google-chrome $param 'http://127.0.0.1:9090?clientID=2' &

UDD=$HOME/.config/chrome-nfs/thor3
param="--kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-webgl --enable-accelerated-compositing --user-data-dir=$UDD"
env DISPLAY=:0.3 google-chrome $param 'http://127.0.0.1:9090?clientID=3' &

wait
