#!/bin/sh

global_param="--new-window --window-size=1536,1360 --kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files"

# Launch Audio Manager
UDD=$HOME/.config/chrome-nfs/thor_ja_audio
mkdir -p $UDD/Default
audio_param="--new-window --window-size=768,1360 --allow-file-access-from-files --user-data-dir=$UDD"
env DISPLAY=:0.1 google-chrome $audio_param 'https://localhost:6060/audioManager.html' &

sleep 1.5

# Launch Display (client 0)
UDD=$HOME/.config/chrome-nfs/thor_ja_0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.1 google-chrome $param 'https://localhost:6060?clientID=0' &


sleep 1.5
export DISPLAY=:0.1

# Move Audio Manager to the proper screen
result="$(xdotool search --name 'Audio Manager - Google Chrome')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`

xdotool windowmove ${arr[$lastElem]} 1536 0

# Move Display Client to the proper screen
result="$(xdotool search --name 'Node Test - Google Chrome')"
arr=($result)
aLen=${#arr[@]}
lastElem=`expr $aLen - 1`

xdotool windowmove ${arr[$lastElem]} 1536 0
xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

wait
