#!/bin/sh

global_param="--new-window --window-size=1536,1360 --kiosk --disable-popup-blocking --nfirst-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files"

# Launch Audio Manager
UDD=$HOME/.config/chrome-nfs/thor_tm_audio
mkdir -p $UDD/Default
audio_param="--new-window --window-size=768,1360 --allow-file-access-from-files --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $audio_param 'https://localhost:7070/audioManager.html' &

sleep 1.5

# Launch Display (client 0)
UDD=$HOME/.config/chrome-nfs/thor_tm_0
mkdir -p $UDD/Default
param="$global_param --user-data-dir=$UDD"
env DISPLAY=:0.0 google-chrome $param 'https://localhost:7070?clientID=0' &


sleep 1.5

export DISPLAY=:0.0

# Move mouse around
xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

wait