#!/bin/sh

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO
#

servers="localhost 127.0.0.1 131.193.77.218 iridium.evl.uic.edu iridium.evl.optiputer.net thor.evl.uic.edu thor.evl.optiputer.net dante.evl.uic.edu lyra.evl.uic.edu lyra.evl.optiputer.net"

for f in `echo $servers`
do
	./init_webserver.sh $f
done
