#!/bin/sh

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-linux
#

servers="localhost 127.0.0.1 thor.evl.uic.edu"

for f in `echo $servers`
do
	./init_webserver.sh $f
done
