#!/bin/sh

#
# to generate a list of certificates, add the server name in the list below
# and run ./GO-linux
#

servers="$HOSTNAME localhost 127.0.0.1"

for f in `echo $servers`
do
	./init_webserver.sh $f
done
